# Global defaults and shared exit codes.

readonly SYSREMOTE_VERSION="1.0.0"
readonly PROGRAM_NAME="sysremote"

readonly EX_OK=0
readonly EX_USAGE=2
readonly EX_CONFIG=3
readonly EX_HOST_VALIDATION=4
readonly EX_PRIVILEGE=10
readonly EX_SSH=20
readonly EX_REMOTE=21
readonly EX_NO_TARGETS=30
readonly EX_INVALID_OPTION=100
readonly EX_MISSING_PARAM=101
readonly EX_DEPENDENCY=109
readonly EX_INVALID_PARAM=110
readonly EX_CRON=111

SSH_USER="${USER:-root}"
SSH_PORT="22"
SSH_TIMEOUT="5"
INVENTORY_FILE=""
REQUIRE_ROOT="true"
REMOTE_SUDO="sudo -n"
DEFAULT_SESSION_COMMAND="who"
CONFIG_FILE=""
VERBOSE="false"
DRY_RUN="false"
LOG_DIR="${SYSREMOTE_ROOT_DIR:-.}/logs"
LOG_FILE=""
LOGGING_READY="false"
EXEC_MODE="normal"
THREAD_JOBS="4"
RESTORE_DEFAULTS="false"

DEFAULT_BACKUP_DIR="${SYSREMOTE_ROOT_DIR:-.}/backups"
DEFAULT_RESTORE_DIR="${SYSREMOTE_ROOT_DIR:-.}/restore"
ARCHIVE_DIR="${SYSREMOTE_ROOT_DIR:-.}/archives"
REPORT_DIR="${SYSREMOTE_ROOT_DIR:-.}/reports"
CRON_TAG="sysremote-managed"

SEUIL_ALERTE="80"
GENERER_HTML="true"
NOTIF_DISCORD="false"
DISCORD_WEBHOOK=""
NOTIF_EMAIL="false"
EMAIL_DESTINATAIRE=""
MONITOR_INTERACTIVE="false"

SENSITIVE_FILES=("/etc/passwd" "/etc/shadow" "/etc/sudoers" "/etc/ssh/sshd_config")
KNOWN_PORTS=(22 80 443 3306 5432 6379 8080 8443)

CLI_CONFIG_FILE=""
CLI_CONFIG_EXPLICIT="false"
CLI_INVENTORY_FILE=""
CLI_MULTI_HOSTS=""
CLI_SSH_USER=""
CLI_SSH_PORT=""
CLI_SSH_TIMEOUT=""
CLI_NO_ROOT_CHECK="false"
CLI_LOG_DIR=""

COMMAND=""
COMMAND_ARGS=()
TARGET_HOSTS=()
