services:
  node1:
    build: .
    container_name: sysremote-node1
    hostname: node1
    ports:
      - "2222:22"
    networks:
      sysremote_net:
        ipv4_address: 172.28.0.11
    mem_limit: 128m
    cpus: 0.25

  node2:
    build: .
    container_name: sysremote-node2
    hostname: node2
    ports:
      - "2223:22"
    networks:
      sysremote_net:
        ipv4_address: 172.28.0.12
    mem_limit: 128m
    cpus: 0.25

  node3:
    build: .
    container_name: sysremote-node3
    hostname: node3
    ports:
      - "2224:22"
    networks:
      sysremote_net:
        ipv4_address: 172.28.0.13
    mem_limit: 128m
    cpus: 0.25

networks:
  sysremote_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
